v3.0/jobportal/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.conf import settings
import debug_toolbar
# from django.contrib.auth import views
# from django.views.generic.base import TemplateView    
urlpatterns = [
    url(r'^__debug__/', include(debug_toolbar.urls)),
    url(r'^admin/', admin.site.urls),
    url(r'', include('naukri.urls')),
     url(r'^oauth/', include('social_django.urls', namespace='social')),  # <--
]

v3.0/naukri/urls.py
from django.conf.urls import url
from . import views

app_name='naukri'

urlpatterns = [
     # /
    url(r'^$',views.index,name='index'),
    # login/
    url(r'^login/$', views.mylogin, name='mylogin'),
    # logout/
    # url(r'^accounts/login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^logout/$', views.mylogout, name='mylogout'),
    # /<job_id>/
    url(r'^(?P<job_id>[0-9]+)/$',views.jobdetail,name='jobdetail'),
    # /<job_id>/apply/
    url(r'^(?P<job_id>[0-9]+)/apply/$',views.apply,name='newuser'),
    # /addjob
    url(r'^addjob/$',views.addjob,name='addjob'),
    # /verifycompany
    url(r'^verifycompany/$',views.verifycompany,name='verifycompany'),
    # /<company_id>/addjob
    url(r'^verifycompany/addnewjob/$',views.addnewjob,name='newjob'),
    # /addcompany
    url(r'^addcompany/$',views.addnewcompany,name='newcomp'),
]

v3.0/naukri/models.py
from django.db import models

# Create your models here.
class Company(models.Model):
	company_name = models.CharField(max_length=100)
	company_address = models.CharField(max_length=100)
	description = models.CharField(max_length=100)
	contactno = models.CharField(max_length=10)

	def __str__(self):
		return self.company_name

	
class Job(models.Model):
	company = models.ForeignKey(
		Company,
		on_delete=models.CASCADE,
		related_name = 'job'
	)
	designation = models.CharField(max_length=100)
	hr_name = models.CharField(max_length=100)
	experience = models.CharField(max_length=10)
	vacancy = models.CharField(max_length=100)
	place = models.CharField(max_length=100)
	salary = models.CharField(max_length=100)
	jobtype = models.CharField(max_length=100)
	required_skills = models.CharField(max_length=1000)

	def __str__(self):
		return self.designation

	class Meta:
		ordering = ('designation',)

class Seeker(models.Model):
	s_name = models.CharField(max_length=20,null=False,blank=False)
	jobs =  models.ManyToManyField(Job)
	email = models.EmailField(max_length=100)
	contactno = models.CharField(max_length=10)
	skills = models.CharField(max_length=100)

	def __str__(self):
		return self.s_name

	class Meta:
		ordering = ('s_name',)

v3.0/naukri/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect, HttpResponse
from .models import *
from django.urls import reverse
from django.template import loader,RequestContext
# from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,logout,login
# Create your views here.
# --------------------------------------------------------------------------------------------------------
def mylogin(request):
	msg=[]
	if request.method == 'POST':
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username, password=password)
		if user is not None:
			if user.is_active:
				login(request, user)
				msg.append("login successful")
				return HttpResponseRedirect('/')
			else:
				msg.append("disabled account")
		else:
			msg.append('invalid username/password')
	# else:
	# 	msg.append('Invalid Login')
	return render(request,'naukri/login.html', {'errors': msg})

# this login required decorator is to not allow to any  
# view without authenticating
# @login_required(login_url="login/")

# ----------------------------------------------------------------------------------------------------------

def mylogout(request):
    logout(request)
    # Redirect to a success page.
    return redirect('/')
# ----------------------------------------------------------------------------------------------------------

def index(request):
	alljob = Job.objects.all()
	return render(request, 'naukri/index.html', {'alljob':alljob})
# -----------------------------------------------------------------------------------------------------------

def jobdetail(request,job_id):
	detail = Job.objects.get(pk = job_id)
	return render(request, 'naukri/jobdetail.html', {'detail':detail})
# -----------------------------------------------------------------------------------------------------------

def apply(request, job_id):
	if request.method == 'POST':
		applicant = Seeker.objects.create(
			s_name = request.POST['s_name'],
			email = request.POST['email'],
			contactno = request.POST['contactno'],
			skills = request.POST['skills'])
		applicant.save()
		context = {'applicant':applicant}
	else:
		context = {}
	return render(request, 'naukri/newuser.html',context)
# -------------------------------------------------------------------------------------------------------------

def addjob(request):
	return render(request, 'naukri/verifycompany.html') #<--- problem!!!
# -----------------------------------------------------------------------------------------------------------

def verifycompany(request):
	if request.method == 'POST':
		company_name = request.POST['company_name']
		company_name = list(Company.objects.filter(company_name = company_name))
		if len(company_name) > 0 :
			company_name = company_name[0]
			jobs = company_name.job.all()
			context = {'jobs':jobs}
			template = loader.get_template('naukri/companyview.html')
			return HttpResponse(template.render(context))
		else:
			return HttpResponse('<h2>Company does not exist!</h2>')
	else:
		return HttpResponse('<h2>Invalid request!</h2>')
	return render(request,'naukri/verifycompany.html',{'company_name':company_name})
# -----------------------------------------------------------------------------------------------------------------

def addnewjob(request):
	# return HttpResponse('<h1>adding</h1>')
	if request.method == 'POST':
		newjob = Job.objects.create(
			# company_id = request.POST['Company.objects.get(pk = company_id)'],
			designation = request.POST['designation'],
			hr_name = request.POST['hr_name'],
			experience = request.POST['experience'],
			vacancy = request.POST['vacancy'],
			place = request.POST['place'],
			salary = request.POST['salary'],
			jobtype = request.POST['jobtype'],
			required_skills = request.POST['required_skills'])
		applicant.save()
		context = {'newjob':newjob}
	else:
		context = {}
	return render(request, 'naukri/addnewjob.html',context)
#-------------------------------------------------------------------------------------------------------------------- 

def addnewcompany(request):
	if request.method == 'POST':
		newcomp = Company.objects.create(
			company_name = request.POST['company_name'],
			company_address = request.POST['company_address'],
			description = request.POST['description'],
			contactno = request.POST['contactno'])
		newcomp.save()
		context = {'newcomp':newcomp}
	else:
		context = {}
	return render(request,'naukri/addnewcompany.html',context)
# ------------------------------------------------------------------------------------------------------------------

v3.0/naukri/templates/naukri/addnewcompany.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="{% static 'naukri/style.css' %}">
<title></title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
</head>
<body>


{% block navigation %}
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
    	<a class="navbar-brand" href="{% url 'naukri:index' %}">
    	<img src="{% static 'naukri/images/icon.png' %}" width="30" height="30" alt="Logo">
    </a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="{% url 'naukri:index' %}">Home</a></li>
      <li class="active"><a href="#">Profile</a></li>
      {% if user.is_authenticated %}
      <li><a href="{% url 'naukri:mylogout' %}"><button>Logout</button></a></li>
      {% else %}
      <li><a href="{% url 'naukri:mylogin' %}"><button>Login</button></a></li>
      <li><a href="{% url 'social:begin' 'facebook' %}"><button>Login with Facebook</button></a></li>
      {% endif %}
    </ul>
  </div>
</nav>
{% endblock %}
  
  
<div class="container">
<div class="card">
  <div class="card-body">	
<form method='POST' action=''  autocomplete="off">
	
	{% csrf_token %}
	
	<div class="form-group">
		<p><label for="newcomp.company_name">Company Name*: </label>
			<input id="newcomp.company_name" class="form-control" type="text" name="company_name" maxlength="100" required />
		</p>
	</div>

	<div class="form-group">	
		<p><label for="newcomp.company_address">Company Address*: </label>
			<input id="newcomp.company_address" class="form-control" type="text" name="company_address" maxlength="100" required />
		</p>
	</div>
	
	<div class="form-group">
		<p><label for="newcomp.description">Description*: </label>
			<input id="newcomp.description" class="form-control" type="text" name="description" maxlength="100" required />
		</p>
	</div>
	
	<div class="form-group">
		<p><label for="newcomp.contactno">Contact No.*: </label>
			<input id="newcomp.contactno" class="form-control" type="text" name="contactno" maxlength="12" minlength="10" required />
		</p>
	</div>
	
	<input type= 'submit' class="btn btn-primary mb-2" value='Submit' />
</div>
</form>
</div>
</div>
</body>
</html>

v3.0/naukri/templates/naukri/addnewjob.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="{% static 'naukri/style.css' %}">
<title></title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
</head>
<body>


{% block navigation %}
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
    	<a class="navbar-brand" href="{% url 'naukri:index' %}">
    	<img src="{% static 'naukri/images/icon.png' %}" width="30" height="30" alt="Logo">
    </a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="{% url 'naukri:index' %}">Home</a></li>
      <li class="active"><a href="#">Profile</a></li>
      {% if user.is_authenticated %}
      <li><a href="{% url 'naukri:mylogout' %}"><button>Logout</button></a></li>
      {% else %}
      <li><a href="{% url 'naukri:mylogin' %}"><button>Login</button></a></li>
      <li><a href="{% url 'social:begin' 'facebook' %}"><button>Login with Facebook</button></a></li>
      {% endif %}
    </ul>
  </div>
</nav>
{% endblock %}
  
  

<div class="container">
<div class="card">
 <div class="card-body">
<form method='POST' action='' autocomplete="off" >
	{% csrf_token %}
	<!-- <p><label for="newjob.company">Company id*: </label>
		<input id="newjob.company" type="text" name="company" maxlength="100" required /></p> -->
		<div class="form-group">
			<p><label for="newjob.designation">Designation*: </label>
				<input id="newjob.designation" class="form-control" type="text" name="designation" maxlength="100" required /></p>
		</div>
		<div class="form-group">
			<p><label for="newjob.hr_name">HR Name*: </label>
				<input id="newjob.hr_name" class="form-control" type="text" name="hr_name" maxlength="100" required /></p>
		</div>
			
		<div class="form-group">	
			<p><label for="newjob.experience">Experience*: </label>
				<input id="newjob.experience" class="form-control" type="text" name="experience" maxlength="100" required /></p>
		</div>
		<div class="form-group">
			<p><label for="newjob.vacancy">Vacancy*: </label>
				<input id="newjob.vacancy" class="form-control" type="text" name="vacancy" maxlength="100" required /></p>
		</div>
		<div class="form-group">
			<p><label for="newjob.place">Place*: </label>
				<input id="newjob.place" class="form-control" type="text" name="place" maxlength="100" required /></p>
		</div>
		<div class="form-group">
			<p><label for="newjob.salary">Salary*: </label>
				<input id="newjob.salary" class="form-control" type="text" name="salary" maxlength="100" required /></p>
		</div>
		<div class="form-group">
			<p><label for="newjob.jobtype">Job Type*: </label>
				<input id="newjob.jobtype" class="form-control" type="text" name="jobtype" maxlength="100" required /></p>
		</div>
		<div class="form-group">
			<p><label for="newjob.required_skills">Required Skills*: </label>
				<input id="newjob.required_skills" class="form-control" type="text" name="required_skills" maxlength="100" required /></p>
		</div>

	<input type= 'submit' value='Submit' />
</div>
</form>
</div>
</div>
</body>
</html>

v3.0/naukri/templates/naukri/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="{% static 'naukri/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<title>
    {% if user.is_authenticated %}
        Hi {{ user.username }}!
    {% else %}
        You're not logged in
        
    {% endif %}
</title>
 <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> -->
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

v3.0/naukri/templates/naukri/companyview.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="{% static 'naukri/style.css' %}">
<title></title>
<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
</head>
<body>


{% block navigation %}
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'naukri:index' %}">
      <img src="{% static 'naukri/images/icon.png' %}" width="30" height="30" alt="Logo">
    </a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="{% url 'naukri:index' %}">Home</a></li>
      <li class="active"><a href="#">Profile</a></li>
      {% if user.is_authenticated %}
      <li><a href="{% url 'naukri:mylogout' %}"><button>Logout</button></a></li>
      {% else %}
      <li><a href="{% url 'naukri:mylogin' %}"><button>Login</button></a></li>
      <li><a href="{% url 'social:begin' 'facebook' %}"><button>Login with Facebook</button></a></li>
      {% endif %}
    </ul>
  </div>
</nav>
{% endblock %}
  
  

	{% if jobs %}
<div class="card-deck">
		{% for each in jobs %}
    <div class="card">
       <div class="card-body">
		<div class="card-title"><h2><b>{{ each.designation }}</b></h2></div>
		<ul>
			<div class="card-text"><li><h4><b>Job Type : </b>{{ each.jobtype }}</h4></li></div>
			<div class="card-text"><li><h4><b>Experience : </b>{{ each.experience }} yrs</h4></li></div>
			<div class="card-text"><li><h4><b>Place : </b>{{ each.place }}</h4></li></div>
			<div class="card-text"><li><h4><b>Required Skills : </b>{{ each.required_skills }}</h4></li></div>
			<div class="card-text"><li><h4><b>Salary : </b>{{ each.salary }}</h4></li></div>
			<div class="card-text"><li><h4><b>Contact Person : </b>{{ each.hr_name }}</h4></li></div>
			<div class="card-text"><li><h4><b>Total Vacancy : </b>{{ each.vacancy }}</h4></li></div>
		</ul>
    <div class="card-footer"><small class="text-muted">Last updated 3 mins ago</small></div>
  </div>
  </div>
		{% endfor %}
  </div>
	{% endif %}
<a href="{% url 'naukri:newjob' %}" class="button"><button type="button">Add jobs</button></a>
</body>
</html>

v3.0/naukri/templates/naukri/index.html
{% extends 'naukri/base.html' %}


{% load static %}


{% block content %}


{% block navigation %}
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
    	<a class="navbar-brand" href="{% url 'naukri:index' %}">
    	<img src="{% static 'naukri/images/icon.png' %}" width="30" height="30" alt="Logo">
    </a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="{% url 'naukri:index' %}">Home</a></li>
      <li class="active"><a href="#">Profile</a></li>
      {% if user.is_authenticated %}
      <li><a href="{% url 'naukri:mylogout' %}"><button>Logout</button></a></li>
      {% else %}
      <li><a href="{% url 'naukri:mylogin' %}"><button>Login</button></a></li>
      <li><a href="{% url 'social:begin' 'facebook' %}"><button>Login with <i class="fa fa-facebook-official"></i></button></a></li>
      <li><a href="{% url 'social:begin' 'google-oauth2' %}"><button>Login with <i class="fa fa-google"></i></button></a></li>
      {% endif %}
    </ul>
  </div>
</nav>
{% endblock %}
  
	<!-- {% if user.is_authenticated %}
	         <a href="{% url 'naukri:mylogout' %}"><button>logout</button></a>
	    {% else %}
	        <a href="{% url 'naukri:mylogin' %}"><button>login</button></a>
	       
	    {% endif %} -->

<div class="card-container">
	{% if alljob %}
		{% for each in alljob %}
		<div class="card">
			<div class="card__title">
				<a href="{% url 'naukri:jobdetail' each.id %}"><h2>{{each.designation}}</h2></a>
				<h3>{{ each.company }}</h3>
			</div>
			<div class="card__description">
				<p>Job Type: {{each.jobtype}}<br>Salary: {{each.salary}}/-
				<a href="{% url 'naukri:jobdetail' each.id %}"><button>View Details</button></a></p>
			</div>
		</div>
		{% endfor %}
	{% endif %}
</div>
<a href="{% url 'naukri:newcomp' %}" class="button"><button type="button">Register Company Here</button></a>
<a href="{% url 'naukri:addjob' %}" class="button"><button type="button">Add jobs Here</button></a>
</div>
{% endblock %}

v3.0/naukri/templates/naukri/jobdetail.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="{% static 'naukri/style.css' %}">
<title></title>
<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>


{% block navigation %}
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'naukri:index' %}">
      <img src="{% static 'naukri/images/icon.png' %}" width="30" height="30" alt="Logo">
    </a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="{% url 'naukri:index' %}">Home</a></li>
      <li class="active"><a href="#">Profile</a></li>
      {% if user.is_authenticated %}
      <li><a href="{% url 'naukri:mylogout' %}"><button>Logout</button></a></li>
      {% else %}
      <li><a href="{% url 'naukri:mylogin' %}"><button>Login</button></a></li>
      <li><a href="{% url 'social:begin' 'facebook' %}"><button>Login with Facebook</button></a></li>
      {% endif %}
    </ul>
  </div>
</nav>
{% endblock %}
  
  

<i class="fa fa-address-card-o" style="font-size:48px;color:black"></i>
<h2><b>{{ detail.designation }}</b></h2>
<ul>
	<li><h3><b>Company : {{ detail.company }}</b></h3></li>
	<li><h4><b>Job Type : </b>{{ detail.jobtype }}</h4></li>
	<li><h4><b>Experience : </b>{{ detail.experience }} yrs</h4></li>
	<li><h4><b>Place : </b>{{ detail.place }}</h4></li>
	<li><h4><b>Required Skills : </b>{{ detail.required_skills }}</h4></li>
	<li><h4><b>Salary : </b>{{ detail.salary }}</h4></li>
	<li><h4><b>Contact Person : </b>{{ detail.hr_name }}</h4></li>
	<li><h4><b>Total Vacancy : </b>{{ detail.vacancy }}</h4></li>
</ul>

<a href="{% url 'naukri:newuser' detail.id %}"><button>Apply</button></a>
</body>
</html>

v3.0/naukri/templates/naukri/login.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'naukri/style.css' %}">
    <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
</head>
<body>

{% block navigation %}
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'naukri:index' %}">
      <img src="{% static 'naukri/images/icon.png' %}" width="30" height="30" alt="Logo">
    </a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="{% url 'naukri:index' %}">Home</a></li>
      <li class="active"><a href="#">Profile</a></li>
      {% if user.is_authenticated %}
      <li><a href="{% url 'naukri:mylogout' %}"><button>Logout</button></a></li>
      {% else %}
      <li><a href="{% url 'naukri:mylogin' %}"><button>Login</button></a></li>
      <li><a href="{% url 'social:begin' 'facebook' %}"><button>Login with Facebook<i class="fa fa-facebook-official"></i></button></a></li>
      {% endif %}
    </ul>
  </div>
</nav>
{% endblock %}
  
     <!-- login avatar -->
     <div class="container">
        <div class="card card-container">
            <div class="w-100">
                <img src="{% static 'naukri/images/img_avatar2.png' %}" alt="Avatar" class="profile-img-card">
            </div>
            <form method="post" action="/login/"  autocomplete="off">
    <!-- form -->
            <div class="form-group">
            {% csrf_token %}
                <p>
                <label for="username"><b>Username:</b></label>
                <input type="text" class="form-control" name="username" id="username" placeholder="Enter email">
                </p>
            </div>
            <div class="form-group">
                <p>
                <label for="password"><b>Password:</b></label>
                <input type="password" class="form-control" name="password" id="password" placeholder="Password">
                </p>
            </div>

            <button type="submit" class="btn btn-primary">Login</button>
        </form>
        </div>
    </div>
     {% if errors %}
        <ul>
            {% for error in errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
</html>

v3.0/naukri/templates/naukri/newuser.html
{% if user.is_authenticated %}        
	
	{% load static %}

	<!DOCTYPE html>
	<html>
	<head>
		<link rel="stylesheet" href="{% static 'naukri/style.css' %}">
	<title></title>
	<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
</head>
	<body>

{% block navigation %}
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
    	<a class="navbar-brand" href="{% url 'naukri:index' %}">
    	<img src="{% static 'naukri/images/icon.png' %}" width="30" height="30" alt="Logo">
    </a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="{% url 'naukri:index' %}">Home</a></li>
      <li class="active"><a href="#">Profile</a></li>
      {% if user.is_authenticated %}
      <li><a href="{% url 'naukri:mylogout' %}"><button>Logout</button></a></li>
      {% else %}
      <li><a href="{% url 'naukri:mylogin' %}"><button>Login</button></a></li>
      <li><a href="{% url 'social:begin' 'facebook' %}"><button>Login with Facebook</button></a></li>
      {% endif %}
    </ul>
  </div>
</nav>
{% endblock %}
  


<div class="container">
<div class="card">
  <div class="card-body">
	<form method='POST' action='' autocomplete="off" >
		{% csrf_token %}
		<div class="form-group">
				<p><label for="applicant.s_name">Name*: </label>
					<input id="applicant.s_name" class="form-control" type="text" name="s_name" maxlength="100" placeholder="Your Name"  required /></p>
				</div>

				<div class="form-group">
				<p><label for="applicant.email">Email*: </label>
					<input id="applicant.email" class="form-control" type="text" name="email" maxlength="100" placeholder= "Your Email" required /></p>
				</div>
				<div class="form-group">
				<p><label for="applicant.contactno">Contact number*: </label>
					<input id="applicant.contactno" class="form-control" type="integer" name="contactno" maxlength="12" minlength="10" placeholder="Your Contact no." required /></p>
				</div>

				<div class="form-group">
				<p><label for="applicant.skills">Skills*: </label>
					<input id="applicant.skills" class="form-control" type="text" name="skills" maxlength="100" placeholder="Your Skills" required /></p>
				</div>
				
		<input type= 'submit' value='Submit'/>
	</div>
	</form>
</div>
</div>
	</body>
	</html>
{% else %}
	<h1>You have to login first!</h1>
{% endif %}

v3.0/naukri/templates/naukri/verifycompany.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="{% static 'naukri/style.css' %}">
<title></title>
<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
</head>
<body>


{% block navigation %}
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'naukri:index' %}">
      <img src="{% static 'naukri/images/icon.png' %}" width="30" height="30" alt="Logo">
    </a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="{% url 'naukri:index' %}">Home</a></li>
      <li class="active"><a href="#">Profile</a></li>
      {% if user.is_authenticated %}
      <li><a href="{% url 'naukri:mylogout' %}"><button>Logout</button></a></li>
      {% else %}
      <li><a href="{% url 'naukri:mylogin' %}"><button>Login</button></a></li>
      <li><a href="{% url 'social:begin' 'facebook' %}"><button>Login with Facebook</button></a></li>
      {% endif %}
    </ul>
  </div>
</nav>
{% endblock %}
  


<form method='POST' action='{% url 'naukri:verifycompany' %}' >
	{% csrf_token %}
	
	<p><label for="company_name">Enter company name: </label>
		<input id="company_name" type="text" name="company_name" maxlength="100" required /></p>
	
	<input type= 'submit' value='Submit' />
</form>
</body>
</html>